spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: sudee
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false